version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
    - location: scripts/stop_app
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/apply_migrations
      timeout: 300
      runas: root
    - location: scripts/collect_staticfiles
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_app
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
