# Generated by Django 3.1 on 2020-08-18 18:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localflavor.cl.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='unique', max_length=10, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField(validators=[localflavor.cl.forms.CLRutField.clean])),
                ('dose', models.DecimalField(decimal_places=2, help_text='applied volume in cm3 0.15 <= dose <= 1.0', max_digits=3, validators=[django.core.validators.MinValueValidator(0.15), django.core.validators.MaxValueValidator(1.0)])),
                ('date', models.DateField(help_text='date of vaccination')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.drug')),
            ],
        ),
    ]
