# Generated by Django 3.1 on 2020-08-22 17:41

from django.db import migrations, models
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='rut',
            field=models.CharField(max_length=12, validators=[resources.models.validate_rut]),
        ),
    ]
